# Generated by Django 6.0.4 on 2026-06-10 08:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import notes.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name="Libelle de l'annee")),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('active', models.BooleanField(default=False, verbose_name='Annee active')),
            ],
            options={
                'verbose_name': 'Annee academique',
                'verbose_name_plural': 'Annees academiques',
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('enseignant', 'Enseignant'), ('etudiant', 'Etudiant'), ('superviseur', 'Superviseur'), ('administrateur', 'Administrateur')], default='enseignant', max_length=20)),
                ('preuve_appartenance', models.ImageField(blank=True, null=True, upload_to='preuves_inscription/')),
                ('preuve_validee', models.BooleanField(default=False)),
                ('date_validation_preuve', models.DateTimeField(blank=True, null=True)),
                ('code_activation', models.CharField(blank=True, max_length=8)),
                ('compte_active', models.BooleanField(default=False)),
                ('code_inscription_attribue', models.CharField(blank=True, max_length=8)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=notes.models.generer_code_inscription, max_length=8, unique=True, verbose_name='Code')),
                ('role', models.CharField(choices=[('enseignant', 'Enseignant'), ('etudiant', 'Etudiant'), ('superviseur', 'Superviseur'), ('administrateur', 'Administrateur')], max_length=20, verbose_name='Role attribue')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('date_utilisation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('utilise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_utilises', to=settings.AUTH_USER_MODEL, verbose_name='Utilise par')),
            ],
            options={
                'verbose_name': "Code d'inscription",
                'verbose_name_plural': "Codes d'inscription",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prenom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Telephone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('specialite', models.CharField(blank=True, max_length=150, verbose_name='Specialite')),
                ('grade', models.CharField(blank=True, max_length=100, verbose_name='Grade')),
                ('photo', models.ImageField(blank=True, upload_to='photos_enseignants/', verbose_name='Photo')),
                ('date_recrutement', models.DateTimeField(auto_now_add=True, verbose_name='Date de recrutement')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_enseignant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prenom')),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matricule etudiant')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, verbose_name='Sexe')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Telephone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('photo', models.ImageField(blank=True, upload_to='photos_etudiants/', verbose_name='Photo')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_etudiant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200, verbose_name='Nom')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Coefficient')),
                ('credits', models.PositiveIntegerField(default=0, verbose_name='Credits')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='notes.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Matiere',
                'verbose_name_plural': 'Matieres',
                'ordering': ['ue', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_devoir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note devoir')),
                ('note_examen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note examen')),
                ('note_matiere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note matiere')),
                ('est_publiee', models.BooleanField(default=False, verbose_name='Est publiee')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('statut', models.CharField(choices=[('V', 'Validee'), ('NV', 'Non validee')], default='NV', max_length=2, verbose_name='Statut')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.etudiant', verbose_name='Etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.matiere', verbose_name='Matiere')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_modification', models.CharField(choices=[('NOTE_MODIFIEE', 'Note modifiee'), ('NOTE_CREEE', 'Note creee'), ('NOTE_SUPPRIMEE', 'Note supprimee')], max_length=50, verbose_name='Type de modification')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_modification', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('lu', models.BooleanField(default=False, verbose_name='Alerte lue')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Modifie par')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='notes.matiere', verbose_name='Matiere')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='notes.note', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de debut')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='notes.anneeacademique', verbose_name='Annee academique')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['annee_academique', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libelle')),
                ('type_session', models.CharField(choices=[('SO', 'Session ordinaire'), ('SR', 'Session de rattrapage')], default='SO', max_length=2, verbose_name='Type de session')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='notes.anneeacademique', verbose_name='Annee academique')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='notes.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='ResultatSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('statut', models.CharField(choices=[('V', 'Valide'), ('NV', 'Non valide'), ('NE', 'Note eliminatoire')], default='NV', max_length=2)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_semestres', to='notes.etudiant')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_semestres', to='notes.semestre')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_semestres', to='notes.session')),
            ],
            options={
                'verbose_name': 'Resultat semestre',
                'verbose_name_plural': 'Resultats semestre',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='notes.session', verbose_name='Session'),
        ),
        migrations.CreateModel(
            name='Superviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prenom')),
                ('departement', models.CharField(blank=True, max_length=150, verbose_name='Departement')),
                ('fonction', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'superviseur'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_superviseur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Superviseur',
                'verbose_name_plural': 'Superviseurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('libelle', models.CharField(blank=True, max_length=200, verbose_name='Libelle')),
                ('derogation', models.BooleanField(default=False, verbose_name='Derogation')),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='notes.superviseur', verbose_name='Superviseur')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ue', models.CharField(max_length=20, verbose_name='Code UE')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libelle')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='notes.classe', verbose_name='Classe')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='notes.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': "Unite d'Enseignement",
                'verbose_name_plural': "Unites d'Enseignement",
                'ordering': ['code_ue'],
            },
        ),
        migrations.CreateModel(
            name='ResultatUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_ue', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('statut', models.CharField(choices=[('V', 'Validee'), ('NV', 'Non validee')], default='NV', max_length=2)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_ue', to='notes.etudiant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_ue', to='notes.session')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_ue', to='notes.ue')),
            ],
            options={
                'verbose_name': 'Resultat UE',
                'verbose_name_plural': 'Resultats UE',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.AddField(
            model_name='matiere',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='notes.ue', verbose_name='UE'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['matricule'], name='notes_etudi_matricu_1a16d8_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['etudiant', 'matiere'], name='notes_note_etudian_3ec7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['statut'], name='notes_note_statut_4326cd_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['est_publiee'], name='notes_note_est_pub_7d84ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'matiere')},
        ),
        migrations.AlterUniqueTogether(
            name='semestre',
            unique_together={('numero', 'annee_academique')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['annee_academique', 'semestre', 'type_session'], name='notes_sessi_annee_a_fb910d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('libelle', 'annee_academique', 'semestre', 'type_session')},
        ),
        migrations.AddIndex(
            model_name='resultatsemestre',
            index=models.Index(fields=['etudiant', 'semestre', 'session'], name='notes_resul_etudian_c4a7c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultatsemestre',
            unique_together={('etudiant', 'semestre', 'session')},
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['nom'], name='notes_class_nom_8c7a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='ue',
            index=models.Index(fields=['classe', 'semestre'], name='notes_ue_classe__b59e12_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatue',
            index=models.Index(fields=['etudiant', 'ue', 'session'], name='notes_resul_etudian_d0b6d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultatue',
            unique_together={('etudiant', 'ue', 'session')},
        ),
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['ue', 'session'], name='notes_matie_ue_id_69b456_idx'),
        ),
        migrations.AddIndex(
            model_name='matiere',
            index=models.Index(fields=['enseignant'], name='notes_matie_enseign_4e6e54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'ue', 'session')},
        ),
    ]
