# Generated by Django 6.0.4 on 2026-07-02 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='code_matiere',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code Matière'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='notes.session', verbose_name='Session'),
        ),
    ]
