# Generated by Django 6.0.4 on 2026-07-04 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_matiere_code_matiere_alter_matiere_session'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='note',
            name='notes_note_etudian_3ec7a3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='note',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='notes.session', verbose_name='Session'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('etudiant', 'matiere', 'session')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['etudiant', 'matiere', 'session'], name='notes_note_etudian_bde244_idx'),
        ),
    ]
