# Generated by Django 6.0.4 on 2026-07-04 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_notes_note_etudian_3ec7a3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='statut',
            field=models.CharField(choices=[('V', 'Validee'), ('NV', 'Non validee'), ('NE', 'Eliminatoire')], default='NV', max_length=2, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='resultatue',
            name='statut',
            field=models.CharField(choices=[('V', 'Validee'), ('NV', 'Non validee'), ('NE', 'Eliminatoire')], default='NV', max_length=2),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('SET_PASSWORD', 'Réinitialisation mot de passe'), ('IMPERSONATE', 'Impersonation')], max_length=32)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=64)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit admin",
                'verbose_name_plural': "Journaux d'audit admin",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='notes_admin_actor_i_704d02_idx'), models.Index(fields=['target_user', 'created_at'], name='notes_admin_target__888394_idx'), models.Index(fields=['resource_type', 'created_at'], name='notes_admin_resourc_d0f653_idx'), models.Index(fields=['action', 'created_at'], name='notes_admin_action_6bf581_idx')],
            },
        ),
    ]
